import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { FileText, Eye } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AppShell } from '@/components/training/app-shell';
const resources=[{title:'Nuclear safety principles',type:'Reference guide',detail:'An overview of fundamental nuclear safety principles.'},{title:'Radiation protection glossary',type:'Glossary',detail:'Common terms used in radiation protection training.'},{title:'Safety culture reference guide',type:'Reference guide',detail:'Key concepts for a strong nuclear safety culture.'}];
export const Route=createFileRoute('/resources')({head:()=>({meta:[{title:'Resources | nuclearsafety.net'},{name:'description',content:'Nuclear safety learning guides and reference materials.'},{property:'og:title',content:'Resources | nuclearsafety.net'},{property:'og:description',content:'Training reference guides and supporting documents.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Resources});
function Resources(){const [selected,setSelected]=useState<typeof resources[number]|null>(null);return <AppShell title="Resources"><div className="page-heading"><div><h1>Resources</h1><p className="subtitle">Reference materials to support your learning.</p></div></div>{resources.map(r=><article className="resource-row" key={r.title}><span className="table-course-icon"><FileText size={19}/></span><div className="flex-1"><h2>{r.title}</h2><p>{r.type}</p></div><Button variant="outline" size="sm" onClick={()=>setSelected(r)}><Eye/>Preview</Button></article>)}<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="modal-content"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.type}</DialogDescription><p className="text-sm text-muted-foreground leading-7">{selected?.detail}</p><div className="dialog-note">Sample resource listing. Final documents will be provided before launch.</div></DialogContent></Dialog></AppShell>}
