import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Award, Eye, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AppShell } from '@/components/training/app-shell';
import { courses } from '@/components/training/mock-data';
export const Route=createFileRoute('/certificates')({head:()=>({meta:[{title:'Certificates | nuclearsafety.net'},{name:'description',content:'View your completed training and sample certificates.'},{property:'og:title',content:'Certificates | nuclearsafety.net'},{property:'og:description',content:'Your nuclear safety training achievements.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Certificates});
function Certificates(){const [selected,setSelected]=useState<string|null>(null);return <AppShell title="Certificates"><div className="page-heading"><div><h1>My certificates</h1><p className="subtitle">A record of your completed training.</p></div><span className="badge completed">2 certificates earned</span></div><div className="course-grid">{courses.filter(c=>c.progress===100).map(c=><article className="catalog-card" key={c.id}><div className="catalog-icon"><Award size={38} strokeWidth={1.3}/></div><div className="catalog-card-body"><span className="badge completed"><ShieldCheck size={12}/>Completed</span><h2>{c.title}</h2><p className="text-xs text-muted-foreground">Awarded {c.due}</p><p className="text-xs text-muted-foreground mt-2">James Wilson</p><Button variant="outline" size="sm" className="mt-5" onClick={()=>setSelected(c.title)}><Eye/>View certificate</Button></div></article>)}</div><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="modal-content"><DialogTitle>Certificate preview</DialogTitle><DialogDescription>Sample certificate · Not an official training record</DialogDescription><div className="text-center border border-border py-10 px-5"><ShieldCheck size={38} className="text-primary mx-auto mb-5"/><p className="eyebrow">nuclearsafety.net</p><h2 className="mt-5">Certificate of completion</h2><p className="text-muted-foreground text-sm mt-5">This sample certifies that</p><p className="text-xl font-semibold mt-2">James Wilson</p><p className="text-muted-foreground text-sm mt-5">has completed</p><p className="font-semibold text-primary mt-2">{selected}</p><p className="text-xs text-muted-foreground mt-8">Demonstration only</p></div></DialogContent></Dialog></AppShell>}
